[package]
name = "unixbar"
version = "0.1.0"
authors = [ "Greg V <greg@unrelenting.technology>" ]
keywords = [ "Desktop", "X11" ]
description = "unixbar"
license = "Unlicense"
readme = "README.md"
homepage = "https://github.com/myfreeweb/unixbar"
repository = "https://github.com/myfreeweb/unixbar"

[features]
default = ["systemstat"]

[dependencies]
chrono = "0.2"
nom = "1.2"
systemstat = { version = "0", optional = true }
